### ISSUE TITLE
Corridor.GetFeaturelinesByCode node not working - CivilPython 2.0.0 posible cause

### ISSUE THREAD

**Issue by Lazarica-t** [Autodesk/civilconnection#17]
Hi Paolo,

The old issue with the **Corridor.GetFeaturelinesByCode** node is back it seams. Dynamo gets stuck in a loop and freezez.
Might want to have a look at the latest **CivilPython 2.0.0**.
Previous version **CivilPython 1.5.0** seams to be working fine with the node.

Best regards!

**Comment by EduardLouis** [comment]
The same for me :(

This is because of the file names:
![image](https://user-images.githubusercontent.com/10221704/67011871-0bfa8080-f0f9-11e9-8a52-0ccdbb142b7c.png)
![image](https://user-images.githubusercontent.com/10221704/67011901-1a489c80-f0f9-11e9-95d5-8918aa695086.png)
The name of the exported file is different from that the code search.

**Comment by paoloemilioserra** [comment]
CorridorFeatureLines.xml is generated if the corridor ObjectId is not found in the Civil3D document, otherwise you get the corridor name appended like this: CorridorFeatureLines_<CorridorName>.xml 
https://github.com/Autodesk/civilconnection/blob/master/Src/CivilPython/CivilPython/CivilPython.cs#L510

**Comment by Lazarica-t** [comment]
So.. In conclusion, the **Corridor.GetFeaturelinesByCode** node will not be fixed?! Because right now the only way to make it work is to downgrade to **CivilPython 1.5.0**

KR,

**Comment by paoloemilioserra** [comment]
@Lazarica-t  You should fix your Civil 3D model as it returns a null ObjectId for the Corridor which affects the way the featurelines are extracted.
The modified behaviour is there to improve the performance and stability of the Featureline extraction.
You need to downgrade to a previous release of CivilConnection too for the moment if you cannot have a decent model to work with.

**Comment by Lazarica-t** [comment]
Thank you for the tip @paoloemilioserra !
From your own experience do you have any ideas what may cause this **null ObjectId**, have you encountered this issue?
I'm just trying to figure out what to look for, since I'm not a Civil 3D user by default, but I'm trying to learn it.
