### ISSUE TITLE
Can't connect to civil 3d

### ISSUE THREAD

**Issue by Brett-Townsend** [Autodesk/civilconnection#19]
I have been through the installation for 2018 and 2019 versions of Revit and C3d and cannot get the CivilApplication node to connect to civil 3d.

I have a tried a long list of fixes but always get the same result, can anyone help?

The installation guide says this error is a conflict between versions so i have removed the 2018 version and reinstalled dyanmo but it still doesn't work.

![CivilApp Error](https://user-images.githubusercontent.com/56806964/67169134-2d0eea00-f3f5-11e9-850a-c08c0eb592bb.png)

**Comment by EduardLouis** [comment]
Hi Brett,

This can be a version conflict, but also can be an error if you run CivilConnection in a family environment. The error received is the same error about "ctor...". I had the same error last week but was because I use it in a family not in the project.
@paoloemilioserra - is possible to customize the error if CivilConnection is started in a family and not in the project - users to know that should be used in the project environment?!

**Comment by paoloemilioserra** [comment]
@EduardLouis I'm working on the custom message I'm in the middle of testing other features as well and PLEASE remember this is not my primary job, so you need to be patient for issues fixing.
@Brett-Townsend, please make sure you are using the latest version, I've found a similar problem with 4.0.3 for Revit 2019.
