### ISSUE TITLE
Featureline.Start and Featureline.End Values are a bit off

### ISSUE THREAD

**Issue by Lazarica-t** [Autodesk/civilconnection#6]
Hi!

There might be a bug with the Featureline.Start and Featureline.End blocks, the values I'm getting are a bit off compared to the old version of CivilConnection. 
The correct values should be 1090 and 4340 respectively, as they are defined in the civil corridor.
See attachments bellow:

![Old_Vs](https://user-images.githubusercontent.com/49474519/61793191-35bc4800-ae27-11e9-9871-aa6d9edc0ac3.jpg)
![New_Vs_304](https://user-images.githubusercontent.com/49474519/61793199-38b73880-ae27-11e9-848d-cbde591208e3.jpg)

Kind regards,

**Comment by paoloemilioserra** [comment]
Hi @Lazarica-t, thanks for reaching out, no bugs here. It's just that the stations on the baseline are rounded at the 3rd decimal digit. I'll override the values on the Featureline properties to match those in the Baseline in the next release.

Just a few words to explain what is happening.

Since version 3.0 the method to extract featurelines has changed a lot, now it is exporting the values directly from Civil 3D up to the 13th decimal digit to a temporary XML (you can check in your temp folder, see an example below). This had two main benefits:
1) performance, now it is much MUCH faster
2) It is possible to correctly read Feature lines that are created with a subassembly with a conditional statement, so that the start and end station of the Featureline do not necessarily coincide with the Starting and Ending station of the baseline region.

![image](https://user-images.githubusercontent.com/14221455/61794956-a44ad700-ae22-11e9-8a7f-3b4ce3da980f.png)

Thanks!

**Comment by paoloemilioserra** [comment]
Fixed in 3.0.5

**Comment by Lazarica-t** [comment]
Awesome! You're the best!
Just tested the new vs. and it works like a charm!

Best regards!
